import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Alert, Box, Button, Card, Chip, Divider, Stack, Tab, Tabs, Typography } from '@mui/material';
import { toast } from 'react-toastify';
import PageHeader from '../../features/admin/components/PageHeader';
import { getAuditLogs, getPurchaseOrders, getReturns, getShipments, receivePurchaseOrder, submitPurchaseOrder, updateReturn, updateShipment } from '../../services/adminService';
import { dateTime } from '../../features/admin/utils/format';
import { useAuth } from '../../Context/useAuth';

const RecordList = ({ records, empty, children }) => <Stack spacing={1.5}>{records.length ? records.map(children) : <Typography color="text.secondary">{empty}</Typography>}</Stack>;

export default function AdminOperations() {
  const [tab, setTab] = useState(0); const client = useQueryClient(); const { user } = useAuth();
  const allSections = [{ key: 'returns', label: 'Returns', roles: ['owner', 'admin', 'support', 'fulfillment'] }, { key: 'shipments', label: 'Shipments', roles: ['owner', 'admin', 'fulfillment'] }, { key: 'purchase', label: 'Purchase orders', roles: ['owner', 'admin', 'inventory'] }, { key: 'audit', label: 'Audit log', roles: ['owner', 'admin', 'support', 'fulfillment', 'inventory', 'finance'] }];
  const sections = allSections.filter(section => section.roles.includes(user?.role)); const activeKey = sections[tab]?.key || sections[0]?.key;
  const returns = useQuery({ queryKey: ['admin', 'returns'], queryFn: () => getReturns(), enabled: activeKey === 'returns' });
  const shipments = useQuery({ queryKey: ['admin', 'shipments'], queryFn: () => getShipments(), enabled: activeKey === 'shipments' });
  const purchaseOrders = useQuery({ queryKey: ['admin', 'purchase-orders'], queryFn: () => getPurchaseOrders(), enabled: activeKey === 'purchase' });
  const audits = useQuery({ queryKey: ['admin', 'audit'], queryFn: () => getAuditLogs({ limit: 50 }), enabled: activeKey === 'audit' });
  const mutate = useMutation({ mutationFn: ({ kind, payload }) => kind === 'return' ? updateReturn(payload) : kind === 'shipment' ? updateShipment(payload) : kind === 'submit-po' ? submitPurchaseOrder(payload.id) : receivePurchaseOrder(payload), onSuccess: () => { toast.success('Operation updated'); client.invalidateQueries({ queryKey: ['admin'] }); }, onError: error => toast.error(error.message) });
  const nextReturn = value => ({ requested: 'approved', approved: 'received', in_transit: 'received', received: 'refunded' })[value];
  const nextShipment = value => ({ pending: 'label_created', label_created: 'in_transit', in_transit: 'out_for_delivery', out_for_delivery: 'delivered' })[value];
  const currentQuery = { returns, shipments, purchase: purchaseOrders, audit: audits }[activeKey];
  return <><PageHeader title="Operations" subtitle="Returns, fulfilment, purchasing and audit history" /><Card><Tabs value={Math.min(tab, Math.max(0, sections.length - 1))} onChange={(_event, value) => setTab(value)} variant="scrollable">{sections.map(section => <Tab key={section.key} label={section.label} />)}</Tabs><Divider /><Box sx={{ p: 2 }}>
    {currentQuery?.isError && <Alert severity="error">{currentQuery.error?.message}</Alert>}
    {activeKey === 'returns' && <RecordList records={returns.data || []} empty="No return requests">{record => <Card variant="outlined" key={record._id} sx={{ p: 2 }}><Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" gap={2}><Box><Typography fontWeight={700}>{record.number}</Typography><Typography variant="body2">{record.reason}</Typography><Typography variant="caption">{record.items.length} line(s) · {dateTime(record.createdAt)}</Typography></Box><Stack direction="row" gap={1} alignItems="center"><Chip label={record.status} />{nextReturn(record.status) && <Button disabled={mutate.isPending} onClick={() => mutate.mutate({ kind: 'return', payload: { id: record._id, status: nextReturn(record.status), ...(nextReturn(record.status) === 'received' && { items: record.items.map(item => ({ orderItemId: item.orderItemId, condition: 'resellable', restock: true })) }) } })}>Mark {nextReturn(record.status)}</Button>}{record.status === 'requested' && <Button color="error" onClick={() => mutate.mutate({ kind: 'return', payload: { id: record._id, status: 'rejected' } })}>Reject</Button>}</Stack></Stack></Card>}</RecordList>}
    {activeKey === 'shipments' && <RecordList records={shipments.data || []} empty="No shipments">{record => <Card variant="outlined" key={record._id} sx={{ p: 2 }}><Stack direction="row" justifyContent="space-between" alignItems="center"><Box><Typography fontWeight={700}>{record.number}</Typography><Typography variant="body2">{record.carrier || 'Carrier not assigned'} {record.trackingNumber || ''}</Typography></Box><Stack direction="row" gap={1}><Chip label={record.status} />{nextShipment(record.status) && <Button onClick={() => mutate.mutate({ kind: 'shipment', payload: { id: record._id, status: nextShipment(record.status) } })}>Mark {nextShipment(record.status)}</Button>}</Stack></Stack></Card>}</RecordList>}
    {activeKey === 'purchase' && <RecordList records={purchaseOrders.data || []} empty="No purchase orders">{record => <Card variant="outlined" key={record._id} sx={{ p: 2 }}><Stack direction="row" justifyContent="space-between" alignItems="center"><Box><Typography fontWeight={700}>{record.number}</Typography><Typography variant="body2">{record.supplierId?.name} · {record.currency} {record.subtotal.toFixed(2)}</Typography></Box><Stack direction="row" gap={1}><Chip label={record.status} />{record.status === 'draft' && <Button onClick={() => mutate.mutate({ kind: 'submit-po', payload: { id: record._id } })}>Submit</Button>}{['submitted', 'partially_received'].includes(record.status) && <Button onClick={() => mutate.mutate({ kind: 'receive-po', payload: { id: record._id, items: record.items.filter(item => item.receivedQuantity < item.quantity).map(item => ({ itemId: item._id, quantity: item.quantity - item.receivedQuantity })) } })}>Receive remaining</Button>}</Stack></Stack></Card>}</RecordList>}
    {activeKey === 'audit' && <RecordList records={audits.data?.items || []} empty="No audit records">{record => <Card variant="outlined" key={record._id} sx={{ p: 2 }}><Typography fontWeight={700}>{record.action}</Typography><Typography variant="body2">{record.entityType} · {record.entityId}</Typography><Typography variant="caption">{record.actorId?.email || 'System'} · {dateTime(record.createdAt)}</Typography></Card>}</RecordList>}
  </Box></Card></>;
}
