import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Box, Button, Card, CardContent, CardHeader, Dialog, DialogActions, DialogContent, DialogTitle, Divider, Grid, Stack, Switch, TextField, Typography } from '@mui/material';
import AddIcon from '@mui/icons-material/Add';
import { toast } from 'react-toastify';
import PageHeader from '../../features/admin/components/PageHeader';
import { EmptyState } from '../../features/admin/components/StateBlocks';
import { createBrand, createCollection, getBrands, getCollections, toggleBrandFeatured, toggleCollectionPublished } from '../../services/adminService';

export default function AdminMerchandising() {
  const client = useQueryClient(); const [dialog, setDialog] = useState(null); const [form, setForm] = useState({ name: '', description: '' });
  const brands = useQuery({ queryKey: ['admin', 'brands'], queryFn: () => getBrands({ limit: 100 }) });
  const collections = useQuery({ queryKey: ['admin', 'collections'], queryFn: () => getCollections({ limit: 100 }) });
  const refresh = () => client.invalidateQueries({ queryKey: ['admin'] });
  const create = useMutation({ mutationFn: payload => dialog === 'brand' ? createBrand(payload) : createCollection({ ...payload, type: 'manual', published: false }), onSuccess: () => { toast.success(`${dialog} created`); setDialog(null); setForm({ name: '', description: '' }); refresh(); }, onError: e => toast.error(e.message) });
  const toggle = useMutation({ mutationFn: ({ type, id }) => type === 'brand' ? toggleBrandFeatured(id) : toggleCollectionPublished(id), onSuccess: refresh, onError: e => toast.error(e.message) });
  return <><PageHeader title="Merchandising" subtitle="Organize the storefront with brands and curated collections" action={<Stack direction="row" spacing={1}><Button variant="outlined" onClick={() => setDialog('brand')}>New brand</Button><Button variant="contained" startIcon={<AddIcon />} onClick={() => setDialog('collection')}>New collection</Button></Stack>} />
    <Grid container spacing={2.5}><Grid size={{ xs: 12, lg: 5 }}><Card><CardHeader title="Brands" subheader={`${brands.data?.total || 0} catalog brands`} /><Divider /><CardContent><Stack spacing={1.5}>{!brands.data?.items?.length ? <EmptyState message="No brands yet" /> : brands.data.items.map(item => <Stack key={item._id} direction="row" alignItems="center" spacing={2} sx={{ p: 1.5, border: 1, borderColor: 'divider', borderRadius: 2 }}><Box sx={{ flexGrow: 1 }}><Typography fontWeight={700}>{item.name}</Typography><Typography variant="caption" color="text.secondary">{item.productCount || 0} products · {item.isActive ? 'Active' : 'Hidden'}</Typography></Box><Stack alignItems="center"><Switch checked={Boolean(item.featured)} onChange={() => toggle.mutate({ type: 'brand', id: item._id })} /><Typography variant="caption">Featured</Typography></Stack></Stack>)}</Stack></CardContent></Card></Grid>
      <Grid size={{ xs: 12, lg: 7 }}><Card><CardHeader title="Collections" subheader="Publish seasonal and campaign-ready product groups" /><Divider /><CardContent><Grid container spacing={1.5}>{!collections.data?.items?.length ? <Grid size={{ xs: 12 }}><EmptyState message="No collections yet" /></Grid> : collections.data.items.map(item => <Grid key={item._id} size={{ xs: 12, md: 6 }}><Box sx={{ p: 2, height: '100%', border: 1, borderColor: 'divider', borderRadius: 2 }}><Stack direction="row" justifyContent="space-between"><Typography fontWeight={800}>{item.name}</Typography><Switch size="small" checked={Boolean(item.published)} onChange={() => toggle.mutate({ type: 'collection', id: item._id })} /></Stack><Typography variant="body2" color="text.secondary" sx={{ my: 1 }}>{item.description || 'No description'}</Typography><Typography variant="caption">{item.products?.length || 0} products · {item.type || 'manual'} · {item.published ? 'Published' : 'Draft'}</Typography></Box></Grid>)}</Grid></CardContent></Card></Grid></Grid>
    <Dialog open={Boolean(dialog)} onClose={() => setDialog(null)} fullWidth maxWidth="sm"><DialogTitle>Create {dialog}</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><TextField autoFocus label="Name" value={form.name} onChange={e => setForm(v => ({ ...v, name: e.target.value }))} /><TextField label="Description" multiline minRows={3} value={form.description} onChange={e => setForm(v => ({ ...v, description: e.target.value }))} /></Stack></DialogContent><DialogActions><Button onClick={() => setDialog(null)}>Cancel</Button><Button variant="contained" disabled={!form.name || create.isPending} onClick={() => create.mutate(form)}>Create</Button></DialogActions></Dialog>
  </>;
}
