import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Box, Button, Card, CardContent, CardHeader, Dialog, DialogActions, DialogContent, DialogTitle, Divider, Grid, LinearProgress, MenuItem, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material';
import AddIcon from '@mui/icons-material/Add';
import { toast } from 'react-toastify';
import PageHeader from '../../features/admin/components/PageHeader';
import StatCard from '../../features/admin/components/StatCard';
import StatusChip from '../../features/admin/components/StatusChip';
import { EmptyState } from '../../features/admin/components/StateBlocks';
import { changeCampaignStatus, createCampaign, getActivitySummary, getCampaigns, getMarketingAnalytics, getNewsletterAnalytics, getNewsletterSubscribers, getPopularProducts } from '../../services/adminService';
import { currency, dateTime, number } from '../../features/admin/utils/format';

const initialCampaign = { name: '', description: '', type: 'email', startDate: '', endDate: '', budget: { total: 0, currency: 'USD' }, content: { subject: '', message: '' } };

export default function AdminGrowth() {
  const client = useQueryClient(); const [open, setOpen] = useState(false); const [form, setForm] = useState(initialCampaign);
  const campaigns = useQuery({ queryKey: ['admin', 'campaigns'], queryFn: () => getCampaigns({ limit: 50 }) });
  const subscribers = useQuery({ queryKey: ['admin', 'newsletter'], queryFn: () => getNewsletterSubscribers({ limit: 8 }) });
  const newsletter = useQuery({ queryKey: ['admin', 'newsletter', 'analytics'], queryFn: getNewsletterAnalytics });
  const activity = useQuery({ queryKey: ['admin', 'activity', 'summary'], queryFn: getActivitySummary });
  const popular = useQuery({ queryKey: ['admin', 'activity', 'popular'], queryFn: getPopularProducts });
  const marketing = useQuery({ queryKey: ['admin', 'marketing', 'analytics'], queryFn: () => getMarketingAnalytics() });
  const refresh = () => client.invalidateQueries({ queryKey: ['admin'] });
  const create = useMutation({ mutationFn: createCampaign, onSuccess: () => { toast.success('Campaign created'); setOpen(false); setForm(initialCampaign); refresh(); }, onError: e => toast.error(e.message) });
  const status = useMutation({ mutationFn: changeCampaignStatus, onSuccess: refresh, onError: e => toast.error(e.message) });
  const activeSubscribers = newsletter.data?.activeSubscribers ?? subscribers.data?.items?.filter(s => s.status === 'active').length ?? 0;

  return <><PageHeader title="Growth center" subtitle="Campaigns, audience, newsletter and customer intent" action={<Button startIcon={<AddIcon />} variant="contained" onClick={() => setOpen(true)}>New campaign</Button>} />
    <Grid container spacing={2.5} sx={{ mb: 2.5 }}><Grid size={{ xs: 12, sm: 6, lg: 3 }}><StatCard label="Campaigns" value={number(campaigns.data?.total)} caption="All lifecycle states" /></Grid><Grid size={{ xs: 12, sm: 6, lg: 3 }}><StatCard label="Active subscribers" value={number(activeSubscribers)} caption={`${number(newsletter.data?.totalSubscribers || subscribers.data?.total)} total`} color="success" /></Grid><Grid size={{ xs: 12, sm: 6, lg: 3 }}><StatCard label="Tracked actions" value={number(activity.data?.totalActivities)} caption={`${number(activity.data?.uniqueUserCount)} shoppers`} color="secondary" /></Grid><Grid size={{ xs: 12, sm: 6, lg: 3 }}><StatCard label="Campaign spend" value={currency((marketing.data?.campaigns || []).reduce((s, v) => s + (v.totalSpent || 0), 0))} caption="Across campaigns" color="warning" /></Grid></Grid>
    <Grid container spacing={2.5}><Grid size={{ xs: 12, lg: 8 }}><Card><CardHeader title="Campaign control" subheader="Create and move campaigns through their lifecycle" /><Divider />{campaigns.isLoading ? <LinearProgress /> : !campaigns.data?.items?.length ? <EmptyState message="No campaigns yet" /> : <Box sx={{ overflowX: 'auto' }}><Table><TableHead><TableRow><TableCell>Campaign</TableCell><TableCell>Channel</TableCell><TableCell>Window</TableCell><TableCell>Status</TableCell><TableCell align="right">Actions</TableCell></TableRow></TableHead><TableBody>{campaigns.data.items.map(c => <TableRow key={c._id}><TableCell><Typography fontWeight={700}>{c.name}</Typography><Typography variant="caption" color="text.secondary">{c.description}</Typography></TableCell><TableCell sx={{ textTransform: 'capitalize' }}>{c.type}</TableCell><TableCell>{dateTime(c.startDate)}<br />{dateTime(c.endDate)}</TableCell><TableCell><StatusChip status={c.status} /></TableCell><TableCell align="right">{['draft','paused'].includes(c.status) && <Button size="small" onClick={() => status.mutate({ id: c._id, action: 'start' })}>Start</Button>}{c.status === 'running' && <Button size="small" onClick={() => status.mutate({ id: c._id, action: 'pause' })}>Pause</Button>}{['running','paused'].includes(c.status) && <Button size="small" color="error" onClick={() => status.mutate({ id: c._id, action: 'stop' })}>Stop</Button>}</TableCell></TableRow>)}</TableBody></Table></Box>}</Card></Grid>
      <Grid size={{ xs: 12, lg: 4 }}><Stack spacing={2.5}><Card><CardHeader title="Audience pulse" /><Divider /><CardContent><Stack spacing={1.5}>{subscribers.data?.items?.slice(0, 6).map(s => <Stack key={s._id} direction="row" justifyContent="space-between"><Box><Typography variant="body2">{s.firstName || 'Subscriber'}</Typography><Typography variant="caption" color="text.secondary">{s.email}</Typography></Box><StatusChip status={s.status} /></Stack>)}</Stack></CardContent></Card><Card><CardHeader title="Most viewed products" /><Divider /><CardContent>{!popular.data?.length ? <EmptyState message="No behavior data yet" /> : <Stack spacing={1.5}>{popular.data.slice(0, 6).map((p, i) => <Stack key={p._id || i} direction="row" justifyContent="space-between"><Typography variant="body2">{p.product?.name || p.productName || `Product ${i + 1}`}</Typography><Typography fontWeight={700}>{number(p.viewCount || p.count || p.totalViews)}</Typography></Stack>)}</Stack>}</CardContent></Card></Stack></Grid>
    </Grid>
    <Dialog open={open} onClose={() => setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Create campaign</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><TextField label="Name" value={form.name} onChange={e => setForm(v => ({ ...v, name: e.target.value }))} /><TextField select label="Channel" value={form.type} onChange={e => setForm(v => ({ ...v, type: e.target.value }))}>{['email','sms','push','banner','popup','social','retargeting'].map(v => <MenuItem key={v} value={v}>{v}</MenuItem>)}</TextField><TextField label="Description" multiline minRows={2} value={form.description} onChange={e => setForm(v => ({ ...v, description: e.target.value }))} /><Grid container spacing={2}><Grid size={{ xs: 6 }}><TextField fullWidth type="datetime-local" label="Starts" slotProps={{ inputLabel: { shrink: true } }} value={form.startDate} onChange={e => setForm(v => ({ ...v, startDate: e.target.value }))} /></Grid><Grid size={{ xs: 6 }}><TextField fullWidth type="datetime-local" label="Ends" slotProps={{ inputLabel: { shrink: true } }} value={form.endDate} onChange={e => setForm(v => ({ ...v, endDate: e.target.value }))} /></Grid></Grid><TextField type="number" label="Budget" value={form.budget.total} onChange={e => setForm(v => ({ ...v, budget: { ...v.budget, total: Number(e.target.value) } }))} /><TextField label="Subject / headline" value={form.content.subject} onChange={e => setForm(v => ({ ...v, content: { ...v.content, subject: e.target.value } }))} /><TextField label="Message" multiline minRows={3} value={form.content.message} onChange={e => setForm(v => ({ ...v, content: { ...v.content, message: e.target.value } }))} /></Stack></DialogContent><DialogActions><Button onClick={() => setOpen(false)}>Cancel</Button><Button variant="contained" disabled={!form.name || !form.startDate || !form.endDate || create.isPending} onClick={() => create.mutate(form)}>Create draft</Button></DialogActions></Dialog>
  </>;
}
