import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Alert, Box, Button, Card, CardContent, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Divider, Grid, MenuItem, Stack, Tab, Tabs, TextField, Typography } from '@mui/material';
import { toast } from 'react-toastify';
import PageHeader from '../../features/admin/components/PageHeader';
import { getAdminProducts } from '../../services/adminService';
import {
  autoAssignCustomerGroups, createCustomerGroup, createVariant, deleteCustomerGroup,
  deleteVariant, getAllReferrals, getCustomerGroups, getNotificationAnalytics,
  getVariants, getWebhookLogs, notifyGroup, sendScheduledNotifications, updateVariantStock,
} from '../../services/commerceService';

const List = ({ rows, empty, children }) => <Stack spacing={1.25}>{rows?.length ? rows.map(children) : <Typography color="text.secondary">{empty}</Typography>}</Stack>;
const initialGroup = { name: '', description: '', type: 'default', discountRules: { type: 'none', value: 0, minOrderAmount: 0 }, isActive: true };
const initialVariant = { productId: '', name: '', sku: '', price: 0, stock: 0, trackInventory: true, optionsText: '' };
const initialNotice = { groupType: 'all', title: '', message: '', category: 'system', priority: 'medium' };

export default function AdminPlatform() {
  const [tab, setTab] = useState(0); const [dialog, setDialog] = useState(null); const [group, setGroup] = useState(initialGroup); const [variant, setVariant] = useState(initialVariant); const [notice, setNotice] = useState(initialNotice); const client = useQueryClient();
  const groups = useQuery({ queryKey: ['admin', 'groups'], queryFn: () => getCustomerGroups({ limit: 100 }), enabled: tab === 0 });
  const variants = useQuery({ queryKey: ['admin', 'variants'], queryFn: () => getVariants({ limit: 100 }), enabled: tab === 1 });
  const products = useQuery({ queryKey: ['admin', 'products', 'variant-picker'], queryFn: () => getAdminProducts({ limit: 100 }), enabled: tab === 1 });
  const analytics = useQuery({ queryKey: ['admin', 'notification-analytics'], queryFn: getNotificationAnalytics, enabled: tab === 2 });
  const referrals = useQuery({ queryKey: ['admin', 'referrals'], queryFn: () => getAllReferrals({ limit: 100 }), enabled: tab === 3 });
  const webhooks = useQuery({ queryKey: ['admin', 'webhooks'], queryFn: () => getWebhookLogs({ limit: 100 }), enabled: tab === 4 });
  const refresh = () => client.invalidateQueries({ queryKey: ['admin'] });
  const action = useMutation({ mutationFn: async ({ type, payload }) => {
    if (type === 'create-group') return createCustomerGroup(payload);
    if (type === 'delete-group') return deleteCustomerGroup(payload);
    if (type === 'auto-groups') return autoAssignCustomerGroups();
    if (type === 'create-variant') return createVariant({ ...payload, options: payload.optionsText.split(',').map(value => value.trim()).filter(Boolean).map(value => { const [name, optionValue] = value.split(':'); return { name: name?.trim(), value: optionValue?.trim() }; }), optionsText: undefined });
    if (type === 'stock') return updateVariantStock(payload);
    if (type === 'delete-variant') return deleteVariant(payload);
    if (type === 'notify' || type === 'create-notice') return notifyGroup(payload);
    return sendScheduledNotifications();
  }, onSuccess: (_data, variables) => { toast.success(variables.type === 'notify' ? 'Notifications created' : 'Platform data updated'); setDialog(null); setGroup(initialGroup); setVariant(initialVariant); setNotice(initialNotice); refresh(); }, onError: error => toast.error(error.message) });
  const groupRows = groups.data?.groups || []; const variantRows = variants.data?.variants || []; const referralRows = referrals.data?.referrals || []; const webhookRows = webhooks.data?.logs || [];
  const currentError = [groups, variants, analytics, referrals, webhooks][tab]?.error;
  return <><PageHeader title="Platform features" subtitle="Customer segments, variants, notifications, referrals and integration events" /><Card><Tabs value={tab} onChange={(_e, value) => setTab(value)} variant="scrollable"><Tab label="Customer groups" /><Tab label="Variants" /><Tab label="Notifications" /><Tab label="Referrals" /><Tab label="Webhooks" /></Tabs><Divider /><CardContent>
    {currentError && <Alert severity="error" sx={{ mb: 2 }}>{currentError.message}</Alert>}
    {tab === 0 && <><Stack direction="row" spacing={1} justifyContent="flex-end" sx={{ mb: 2 }}><Button onClick={() => action.mutate({ type: 'auto-groups' })}>Auto-assign customers</Button><Button variant="contained" onClick={() => setDialog('group')}>New group</Button></Stack><Grid container spacing={2}><List rows={groupRows} empty="No customer groups">{item => <Grid key={item._id} size={{ xs: 12, md: 6, lg: 4 }}><Card variant="outlined"><CardContent><Stack direction="row" justifyContent="space-between"><Typography fontWeight={800}>{item.name}</Typography><Chip size="small" label={item.type} /></Stack><Typography variant="body2" color="text.secondary" sx={{ my: 1 }}>{item.description || 'No description'}</Typography><Typography variant="body2">{item.customerCount || 0} customers · {item.formattedDiscount || `${item.discountRules?.value || 0}${item.discountRules?.type === 'percentage' ? '%' : ''}`}</Typography><Button color="error" size="small" sx={{ mt: 1 }} onClick={() => action.mutate({ type: 'delete-group', payload: item._id })}>Delete</Button></CardContent></Card></Grid>}</List></Grid></>}
    {tab === 1 && <><Box textAlign="right" sx={{ mb: 2 }}><Button variant="contained" onClick={() => setDialog('variant')}>New variant</Button></Box><List rows={variantRows} empty="No product variants">{item => <Card variant="outlined" key={item._id} sx={{ p: 2 }}><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" gap={2}><Box><Typography fontWeight={800}>{item.productId?.name} — {item.name}</Typography><Typography variant="body2" color="text.secondary">{item.sku} · ${Number(item.price).toFixed(2)} · {item.options?.map(v => `${v.name}: ${v.value}`).join(', ')}</Typography></Box><Stack direction="row" alignItems="center" spacing={1}><TextField size="small" type="number" label="Stock" defaultValue={item.stock} sx={{ width: 110 }} onBlur={event => { const stock = Number(event.target.value); if (stock !== item.stock) action.mutate({ type: 'stock', payload: { id: item._id, stock } }); }} /><Button color="error" onClick={() => action.mutate({ type: 'delete-variant', payload: item._id })}>Delete</Button></Stack></Stack></Card>}</List></>}
    {tab === 2 && <><Stack direction="row" spacing={1} justifyContent="flex-end" sx={{ mb: 2 }}><Button onClick={() => action.mutate({ type: 'send' })}>Send scheduled now</Button><Button variant="contained" onClick={() => setDialog('notice')}>Compose notification</Button></Stack><Grid container spacing={2}>{(Array.isArray(analytics.data) ? analytics.data : []).map((item, index) => <Grid key={index} size={{ xs: 12, sm: 6, lg: 4 }}><Card variant="outlined"><CardContent><Typography fontWeight={800}>{item._id?.type || 'Notification'}</Typography><Typography variant="body2">{item._id?.category} · {item.total} total · {Number(item.readRate || 0).toFixed(0)}% read</Typography></CardContent></Card></Grid>)}</Grid></>}
    {tab === 3 && <List rows={referralRows} empty="No referrals">{item => <Card variant="outlined" key={item._id} sx={{ p: 2 }}><Stack direction="row" justifyContent="space-between"><Box><Typography fontWeight={800}>{item.referrerId?.email || 'Unknown referrer'} → {item.referredId?.email || item.referredEmail}</Typography><Typography variant="body2">{item.referralCode} · {item.totalClicks || 0} clicks · {item.totalConversions || 0} conversions</Typography></Box><Chip label={item.status} /></Stack></Card>}</List>}
    {tab === 4 && <List rows={webhookRows} empty="No webhook events">{item => <Card variant="outlined" key={item._id} sx={{ p: 2 }}><Stack direction="row" justifyContent="space-between"><Box><Typography fontWeight={800}>{item.event}</Typography><Typography variant="body2">{item.source} · {item.eventId}</Typography><Typography variant="caption">{new Date(item.createdAt).toLocaleString()}</Typography></Box><Chip label={item.status} /></Stack></Card>}</List>}
  </CardContent></Card>
  <Dialog open={Boolean(dialog)} onClose={() => setDialog(null)} fullWidth maxWidth="sm"><DialogTitle>{dialog === 'group' ? 'New customer group' : dialog === 'variant' ? 'New product variant' : 'Compose notification'}</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}>
    {dialog === 'group' && <><TextField label="Name" value={group.name} onChange={e => setGroup(v => ({ ...v, name: e.target.value }))} /><TextField label="Description" value={group.description} onChange={e => setGroup(v => ({ ...v, description: e.target.value }))} /><TextField select label="Type" value={group.type} onChange={e => setGroup(v => ({ ...v, type: e.target.value }))}>{['default','vip','wholesale','retail','corporate','affiliate'].map(v => <MenuItem key={v} value={v}>{v}</MenuItem>)}</TextField><TextField select label="Discount type" value={group.discountRules.type} onChange={e => setGroup(v => ({ ...v, discountRules: { ...v.discountRules, type: e.target.value } }))}>{['none','percentage','fixed'].map(v => <MenuItem key={v} value={v}>{v}</MenuItem>)}</TextField><TextField type="number" label="Discount value" value={group.discountRules.value} onChange={e => setGroup(v => ({ ...v, discountRules: { ...v.discountRules, value: Number(e.target.value) } }))} /></>}
    {dialog === 'variant' && <><TextField select label="Product" value={variant.productId} onChange={e => setVariant(v => ({ ...v, productId: e.target.value }))}>{products.data?.items?.map(v => <MenuItem key={v._id || v.id} value={v._id || v.id}>{v.name}</MenuItem>)}</TextField><TextField label="Variant name" value={variant.name} onChange={e => setVariant(v => ({ ...v, name: e.target.value }))} /><TextField label="SKU" value={variant.sku} onChange={e => setVariant(v => ({ ...v, sku: e.target.value }))} /><TextField label="Options (e.g. Size: M, Color: Blue)" value={variant.optionsText} onChange={e => setVariant(v => ({ ...v, optionsText: e.target.value }))} /><Stack direction="row" spacing={2}><TextField fullWidth type="number" label="Price" value={variant.price} onChange={e => setVariant(v => ({ ...v, price: Number(e.target.value) }))} /><TextField fullWidth type="number" label="Stock" value={variant.stock} onChange={e => setVariant(v => ({ ...v, stock: Number(e.target.value) }))} /></Stack></>}
    {dialog === 'notice' && <><TextField select label="Audience" value={notice.groupType} onChange={e => setNotice(v => ({ ...v, groupType: e.target.value }))}>{['all','customer','admin'].map(v => <MenuItem key={v} value={v}>{v}</MenuItem>)}</TextField><TextField label="Title" value={notice.title} onChange={e => setNotice(v => ({ ...v, title: e.target.value }))} /><TextField multiline minRows={4} label="Message" value={notice.message} onChange={e => setNotice(v => ({ ...v, message: e.target.value }))} /><Stack direction="row" spacing={2}><TextField fullWidth select label="Category" value={notice.category} onChange={e => setNotice(v => ({ ...v, category: e.target.value }))}>{['order','payment','product','marketing','support','system','account'].map(v => <MenuItem key={v} value={v}>{v}</MenuItem>)}</TextField><TextField fullWidth select label="Priority" value={notice.priority} onChange={e => setNotice(v => ({ ...v, priority: e.target.value }))}>{['low','medium','high','urgent'].map(v => <MenuItem key={v} value={v}>{v}</MenuItem>)}</TextField></Stack></>}
  </Stack></DialogContent><DialogActions><Button onClick={() => setDialog(null)}>Cancel</Button><Button variant="contained" disabled={action.isPending} onClick={() => action.mutate({ type: `create-${dialog}`, payload: dialog === 'group' ? group : dialog === 'variant' ? variant : notice })}>Create</Button></DialogActions></Dialog></>;
}
